config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get "tasks", to: "tasks#index"
  get "tasks/new", to: "tasks#new"
  get "tasks/:id", to: "tasks#show", as: :task
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :edit_task
  patch "tasks/:id", to: "tasks#update"
  delete "tasks/:id", to: "tasks#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new # Needed to instantiate the form_for
  end

  def create
    @task = Task.new(task_params)
    @task.save # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    # No need for app/views/tasks/update.html.erb
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="page-container mx-4 my-3" >
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details%>
  <% unless task.new_record? %>
    <%= f.check_box :completed %>
    <%= f.label :completed %>
  <% end %>
  <%= f.submit class: "btn btn-primary fw-bold submit-btn" %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
<%= render "form", task: @task %>

<div class="border-top pt-2 mt-4">
  <%= link_to tasks_path do %>
    <p><i class="fas fa-history"></i></i> Back to list</p>
  <% end %>
</div>

app/views/tasks/index.html.erb
<h1>My tasks</h1>
<ul class="list-unstyled">
  <% @tasks.each do |task| %>
    <li><% if task.completed %>
          <i class="fa-regular fa-square-check"></i>
        <% else %>
          <i class="fa-regular fa-square"></i>
        <% end %>
        <%= link_to task.title, task_path(task) %><span class="set-blue-color"> • </span>
    <%= link_to task_path(task), data: {turbo_method: :delete, turbo_confirm: "Delete #{task.title}?"} do %>
      <i class="fas fa-trash-alt"></i>
    <% end %>
    </li>
  <% end %>
</ul>
<div class="border-top pt-2">
  <%= link_to tasks_new_path do %>
    <p><i class="fa-solid fa-plus"></i> Add a new task</p>
  <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New task</h1>
<%= render "form", task: @task %>

<div class="border-top pt-2 mt-4">
  <%= link_to tasks_path do %>
    <p><i class="fas fa-history"></i></i> Back to list</p>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="d-flex justify-content-between">
  <h1><%= @task.title %></h1>
  <%= link_to edit_task_path do %>
    <h2 class="btn btn-light py-2"><i class="fas fa-edit"></i> Edit this task</h2>
  <% end %>
</div>
<div class="card w-100 my-3 bg-light">
  <p class="p-3 m-0"><%= @task.details %></p>
</div>
<% if @task.completed %>
  <p><i class="fa-regular fa-square-check"></i> This task is completed</p>
<% else %>
  <p><i class="fa-regular fa-square"></i> This task is not completed yet</p>
<% end %>

<div class="border-top pt-2">
  <%= link_to tasks_path do %>
    <p><i class="fas fa-history"></i></i> Back to list</p>
  <% end %>
</div>